In [38]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
import itertools
from sklearn.model_selection import cross_val_score
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [2]:
df=pd.read_excel("Stopwords_Removed_Ticket_TypeWithoutClient.xlsx")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79053 entries, 0 to 79052
Data columns (total 10 columns):
Incident: Number      79053 non-null int64
Opened Date           79053 non-null datetime64[ns]
Queue                 79053 non-null object
Category              79053 non-null object
Client Location       69515 non-null object
Template              47271 non-null object
Request Definition    28023 non-null object
Short Description     79053 non-null object
Ticket_Type           79053 non-null object
Description1          78956 non-null object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 6.0+ MB


In [4]:
df.dropna(subset=["Description1"],inplace=True)

In [5]:
df=df[df['Ticket_Type']=='Request']

In [6]:
X_train, X_test, y_train, y_test =  train_test_split(df['Description1'], df['Category'], test_size=0.20, random_state=42)

In [13]:
pipeline = Pipeline([
        ('bow', CountVectorizer(ngram_range=(1,2))),  # strings to token integer counts
        ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
        #('Normalize', preprocessing.Normalizer()),
        ('c',GradientBoostingClassifier(loss='deviance',n_estimators=300,learning_rate=0.01,max_depth=1,)),  
    ])

In [7]:
pipeline = Pipeline([
        ('bow', CountVectorizer(ngram_range=(1,2))),  # strings to token integer counts
        ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
        #('Normalize', preprocessing.Normalizer()),
        ('c',svm.SVC(kernel='linear',probability=True)),  
    ])

In [35]:
pipeline = Pipeline([
        ('bow', CountVectorizer(ngram_range=(1,2))),  # strings to token integer counts
        ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
        #('Normalize', preprocessing.Normalizer()),
        ('c',XGBClassifier()),  
    ])

In [14]:
pipeline.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('bow', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_...      presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False))])

In [15]:
pred=pipeline.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print("Accuracy : ",accuracy_score(pred,y_test))

[[16  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0 25 ...  0  0  0]
 ...
 [ 0  0  0 ... 27  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0 12]]
                                  precision    recall  f1-score   support

         Add New Virtual Machine       0.64      0.47      0.54        34
                          Apttus       0.50      0.50      0.50         2
                    Audio-Visual       0.81      0.76      0.78        33
                          Backup       0.46      0.68      0.55        19
                         Browser       1.00      1.00      1.00         1
           Business Applications       0.00      0.00      0.00         2
                            CCMS       0.98      0.92      0.95       193
                             COD       0.78      0.87      0.82       137
                         COE-VPN       0.93      0.92      0.92       133
                             COS       1.00      0.50      0.67         2
                         CPM/

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
pipeline.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('bow', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_...',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False))])

In [9]:
pred=pipeline.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print("Accuracy : ",accuracy_score(pred,y_test))

[[24  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 29  0  0]
 [ 0  0  0 ...  0  3  0]
 [ 0  0  0 ...  0  0 21]]
                                  precision    recall  f1-score   support

         Add New Virtual Machine       0.73      0.71      0.72        34
                          Apttus       0.50      0.50      0.50         2
                    Audio-Visual       0.93      0.79      0.85        33
                          Backup       0.87      0.68      0.76        19
                         Browser       0.00      0.00      0.00         1
           Business Applications       0.00      0.00      0.00         2
                            CCMS       0.98      0.96      0.97       193
                             COD       0.81      0.89      0.85       137
                         COE-VPN       0.95      0.92      0.93       133
                             COS       0.00      0.00      0.00         2
                         CPM/

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [32]:
pipeline.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('bow', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_...
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1))])

In [33]:
pred=pipeline.predict(X_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print("Accuracy : ",accuracy_score(pred,y_test))

[[20  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0 25 ...  0  0  0]
 ...
 [ 0  0  0 ... 27  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0 18]]
                                  precision    recall  f1-score   support

         Add New Virtual Machine       0.62      0.59      0.61        34
                          Apttus       0.50      0.50      0.50         2
                    Audio-Visual       0.93      0.76      0.83        33
                          Backup       0.64      0.74      0.68        19
                         Browser       0.00      0.00      0.00         1
           Business Applications       0.00      0.00      0.00         2
                            CCMS       0.97      0.93      0.95       193
                             COD       0.80      0.86      0.83       137
                         COE-VPN       0.93      0.92      0.93       133
                             COS       0.00      0.00      0.00         2
                         CPM/

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [45]:
param_grid = {'c__max_depth':[0,1,2],'c__n_estimator':[100,150,200,250],'c__learning_rate':[0.1,1,2], 'c__gamma':[0.1,1, 10, 100, 1000]} 

In [46]:
grid_search = GridSearchCV(pipeline,param_grid,refit=True, verbose=3)

In [ ]:

grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 180 candidates, totalling 540 fits


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=100 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.4min remaining:    0.0s


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=100, score=0.12444919214848445, total= 1.2min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=100 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  3.2min remaining:    0.0s


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=100, score=0.1249832372267668, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=100 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=100, score=0.12557262193478846, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=150 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=150, score=0.12444919214848445, total= 1.3min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=150 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=150, score=0.1249832372267668, total= 1.5min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=150 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=150, score=0.12557262193478846, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=200 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=200, score=0.12444919214848445, total= 1.3min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=200 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=200, score=0.1249832372267668, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=200 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=200, score=0.12557262193478846, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=250 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=250, score=0.12444919214848445, total= 1.2min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=250 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=250, score=0.1249832372267668, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=250 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=0, c__n_estimator=250, score=0.12557262193478846, total= 1.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=100 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=100, score=0.7827480304446521, total= 8.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=100 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=100, score=0.8015287649188682, total= 9.4min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=100 


C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[CV]  c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=100, score=0.7922392886014551, total= 8.9min
[CV] c__gamma=0.1, c__learning_rate=0.1, c__max_depth=1, c__n_estimator=150 
